use_frameworks!

target 'JJStaggeredGridCollectionView_Example' do
  pod 'JJStaggeredGridCollectionView', :path => '../'
  pod 'Alamofire'
  pod 'Moya'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'RxSwift'
  pod 'RxOptional'
  pod 'Kingfisher'

  target 'JJStaggeredGridCollectionView_Tests' do
    inherit! :search_paths

    pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
